springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: First API - Swagger
    description: Documentação das APIs da minha aplicação
    version: 1.0.0